name: Mirror to public

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  
      - name: Make sure secrets are not tracked
        run: |
          git rm -r --cached .env* 2>/dev/null || true
          echo -e "\n.env\n.env.*\n.supabase/*\n" >> .gitignore

      - name: Push to public mirror
        env:
          PUBLIC_URL: https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/hni1991/arena-fa-public.git
        run: |
          git remote add mirror "$PUBLIC_URL" || git remote set-url mirror "$PUBLIC_URL"
 
          git push --mirror mirror


